# sonar-project.properties

sonar.projectKey=Haiyahhh_DVWA
sonar.organization=haiyahhh

# Change this to '.' to scan the whole codebase
# For the sake of proving that the quality gate works, we narrow the scope down to 'vulnerabilities/exec' folder
sonar.sources=vulnerabilities/exec/

sonar.exclusions=vendor/**, tests/**, *.sql

sonar.language=php